---Tao ID NhaCungCap---
CREATE OR REPLACE TRIGGER TAO_ID_NHA_CUNG_CAP BEFORE INSERT ON NhaCungCap
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMNCC NUMBER;
ID CHAR(5);
CHUOISOKHONG VARCHAR(5) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaNCC)INTO DEMNCC FROM NhaCungCap;
    DEMNCC := DEMNCC +  1;
    LENGTHID := (5 - ((LENGTH(DEMNCC) + LENGTH('CC'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('CC',CHUOISOKHONG||DEMNCC);
    SELECT COUNT(MaNCC) INTO DEMID FROM NhaCungCap WHERE MaNCC = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMNCC := DEMNCC + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 5 - ((LENGTH(DEMNCC) + LENGTH('CC')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('CC',CHUOISOKHONG||DEMNCC);
        SELECT COUNT(MaNCC) INTO DEMID FROM NhaCungCap WHERE MaNCC = ID;
    END LOOP;
    :NEW.MaNCC := ID;
END;

---Tao ID ThanhPho---
CREATE OR REPLACE TRIGGER TAO_ID_THANH_PHO BEFORE INSERT ON ThanhPho
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMTP NUMBER;
ID CHAR(5);
CHUOISOKHONG VARCHAR(5) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaThanhPho)INTO DEMTP FROM ThanhPho;
    DEMTP := DEMTP +  1;
    LENGTHID := (5 - ((LENGTH(DEMTP) + LENGTH('TP'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('TP',CHUOISOKHONG||DEMTP);
    SELECT COUNT(MaThanhPho) INTO DEMID FROM ThanhPho WHERE MaThanhPho = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMTP := DEMTP + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 5 - ((LENGTH(DEMTP) + LENGTH('TP')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('TP',CHUOISOKHONG||DEMTP);
        SELECT COUNT(MaThanhPho) INTO DEMID FROM ThanhPho WHERE MaThanhPho = ID;
    END LOOP;
    :NEW.MaThanhPho := ID;
END;

---Tao ID KhuyenMai---
CREATE OR REPLACE TRIGGER TAO_ID_KHUYEN_MAI BEFORE INSERT ON KhuyenMai
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMKM NUMBER;
ID CHAR(10);
CHUOISOKHONG VARCHAR(8) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaKhuyenMai)INTO DEMKM FROM KhuyenMai;
    DEMKM := DEMKM +  1;
    LENGTHID := (10 - ((LENGTH(DEMKM) + LENGTH('KM'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('KM',CHUOISOKHONG||DEMKM);
    SELECT COUNT(MaKhuyenMai) INTO DEMID FROM KhuyenMai WHERE MaKhuyenMai = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMKM := DEMKM + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 5 - ((LENGTH(DEMKM) + LENGTH('KM')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('TP',CHUOISOKHONG||DEMKM);
        SELECT COUNT(MaKhuyenMai) INTO DEMID FROM KhuyenMai WHERE MaKhuyenMai = ID;
    END LOOP;
    :NEW.MaKhuyenMai := ID;
END;

---Tao ID DANHMUC---
CREATE OR REPLACE TRIGGER TAO_ID_DANH_MUC BEFORE INSERT ON DanhMuc
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMDM NUMBER;
ID CHAR(5);
CHUOISOKHONG VARCHAR(3) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaDanhMuc)INTO DEMDM FROM DanhMuc;
    DEMDM := DEMDM +  1;
    LENGTHID := (5 - ((LENGTH(DEMDM) + LENGTH('DM'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('DM',CHUOISOKHONG||DEMDM);
    SELECT COUNT(MaDanhMuc) INTO DEMID FROM DanhMuc WHERE MaDanhMuc = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMDM := DEMDM + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 5 - ((LENGTH(DEMDM) + LENGTH('DM')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('TP',CHUOISOKHONG||DEMDM);
        SELECT COUNT(MaDanhMuc) INTO DEMID FROM DanhMuc WHERE MaDanhMuc = ID;
    END LOOP;
    :NEW.MaDanhMuc := ID;
END;

---Tao ID LOAI---
CREATE OR REPLACE TRIGGER TAO_ID_LOAI BEFORE INSERT ON Loai
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMLOAI NUMBER;
ID CHAR(5);
CHUOISOKHONG VARCHAR(4) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaLoai)INTO DEMLOAI FROM Loai;
    DEMLOAI := DEMLOAI +  1;
    LENGTHID := (5 - ((LENGTH(DEMLOAI) + LENGTH('L'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('L',CHUOISOKHONG||DEMLOAI);
    SELECT COUNT(MaLoai) INTO DEMID FROM Loai WHERE MaLoai = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMLOAI := DEMLOAI + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 5 - ((LENGTH(DEMLOAI) + LENGTH('L')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('L',CHUOISOKHONG||DEMLOAI);
        SELECT COUNT(MaLoai) INTO DEMID FROM Loai WHERE MaLoai = ID;
    END LOOP;
    :NEW.MaLoai := ID;
END;

---Tao ID SANPHAM---
CREATE OR REPLACE TRIGGER TAO_ID_SAN_PHAM BEFORE INSERT ON SanPham
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMSP NUMBER;
ID CHAR(10);
CHUOISOKHONG VARCHAR(8) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaSanPham)INTO DEMSP FROM SanPham;
    DEMSP := DEMSP +  1;
    LENGTHID := (10 - ((LENGTH(DEMSP) + LENGTH('SP'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('SP',CHUOISOKHONG||DEMSP);
    SELECT COUNT(MaSanPham) INTO DEMID FROM SanPham WHERE MaSanPham = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMSP := DEMSP + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 5 - ((LENGTH(DEMSP) + LENGTH('SP')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('SP',CHUOISOKHONG||DEMSP);
        SELECT COUNT(MaSanPham) INTO DEMID FROM SanPham WHERE MaSanPham = ID;
    END LOOP;
    :NEW.MaSanPham := ID;
END;

---Tao ID CHUCVU---
CREATE OR REPLACE TRIGGER TAO_ID_CHUC_VU BEFORE INSERT ON ChucVu
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMCV NUMBER;
ID CHAR(5);
CHUOISOKHONG VARCHAR(3) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaChucVu)INTO DEMCV FROM ChucVu;
    DEMCV := DEMCV +  1;
    LENGTHID := (5 - ((LENGTH(DEMCV) + LENGTH('CV'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('CV',CHUOISOKHONG||DEMCV);
    SELECT COUNT(MaChucVu) INTO DEMID FROM ChucVu WHERE MaChucVu = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMCV := DEMCV + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 5 - ((LENGTH(DEMCV) + LENGTH('CV')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('CV',CHUOISOKHONG||DEMCV);
        SELECT COUNT(MaChucVu) INTO DEMID FROM ChucVu WHERE MaChucVu = ID;
    END LOOP;
    :NEW.MaChucVu := ID;
END;

---Tao ID NHANVIEN---
CREATE OR REPLACE TRIGGER TAO_ID_NHAN_VIEN BEFORE INSERT ON NhanVien
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMNV NUMBER;
ID CHAR(10);
CHUOISOKHONG VARCHAR(8) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaNhanVien)INTO DEMNV FROM NhanVien;
    DEMNV := DEMNV +  1;
    LENGTHID := (10 - ((LENGTH(DEMNV) + LENGTH('NV'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('NV',CHUOISOKHONG||DEMNV);
    SELECT COUNT(MaNhanVien) INTO DEMID FROM NhanVien WHERE MaNhanVien = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMNV := DEMNV + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 10 - ((LENGTH(DEMNV) + LENGTH('NV')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('NV',CHUOISOKHONG||DEMNV);
        SELECT COUNT(MaNhanVien) INTO DEMID FROM NhanVien WHERE MaNhanVien = ID;
    END LOOP;
    :NEW.MaNhanVien := ID;
END;

---Tao ID CUAHANG---
CREATE OR REPLACE TRIGGER TAO_ID_CUA_HANG BEFORE INSERT ON CuaHang
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMCH NUMBER;
ID CHAR(5);
CHUOISOKHONG VARCHAR(3) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaCuaHang)INTO DEMCH FROM CuaHang;
    DEMCH := DEMCH +  1;
    LENGTHID := (5 - ((LENGTH(DEMCH) + LENGTH('CH'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('CH',CHUOISOKHONG||DEMCH);
    SELECT COUNT(MaCuaHang) INTO DEMID FROM CuaHang WHERE MaCuaHang = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMCH := DEMCH + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 5 - ((LENGTH(DEMCH) + LENGTH('CH')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('CH',CHUOISOKHONG||DEMCH);
        SELECT COUNT(MaCuaHang) INTO DEMID FROM CuaHang WHERE MaCuaHang = ID;
    END LOOP;
    :NEW.MaCuaHang := ID;
END;

---Tao ID KHO---
CREATE OR REPLACE TRIGGER TAO_ID_KHO BEFORE INSERT ON Kho
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMKHO NUMBER;
ID CHAR(5);
CHUOISOKHONG VARCHAR(4) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaKho)INTO DEMKHO FROM Kho;
    DEMKHO := DEMKHO +  1;
    LENGTHID := (5 - ((LENGTH(DEMKHO) + LENGTH('K'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('K',CHUOISOKHONG||DEMKHO);
    SELECT COUNT(MaKho) INTO DEMID FROM Kho WHERE MaKho = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMKHO := DEMKHO + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 5 - ((LENGTH(DEMKHO) + LENGTH('K')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('K',CHUOISOKHONG||DEMKHO);
        SELECT COUNT(MaKho) INTO DEMID FROM Kho WHERE MaKho = ID;
    END LOOP;
    :NEW.MaKho := ID;
END;

---Tao ID PHIEUNHAP---
CREATE OR REPLACE TRIGGER TAO_ID_PHIEU_NHAP BEFORE INSERT ON PhieuNhap
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
ID CHAR(10);
stt VARCHAR(10);
CHUOISOKHONG VARCHAR(8) := '0';
I NUMBER := 0;
LENGTHID NUMBER;
BEGIN
    stt := TRIM(:NEW.MaPhieuNhap);
    LENGTHID := (10 - ((LENGTH((stt) ) + LENGTH('PN'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('PN',CHUOISOKHONG||stt);
    :NEW.MaPhieuNhap := ID;
END;

/*
---Tao ID PHIEUNHAP---
CREATE OR REPLACE TRIGGER TAO_ID_PHIEU_NHAP BEFORE INSERT ON PhieuNhap
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMPN NUMBER;
ID CHAR(10);
CHUOISOKHONG VARCHAR(8) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaPhieuNhap)INTO DEMPN FROM PhieuNhap;
    DEMPN := DEMPN +  1;
    LENGTHID := (10 - ((LENGTH(DEMPN) + LENGTH('PN'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('PN',CHUOISOKHONG||DEMPN);
    SELECT COUNT(MaPhieuNhap) INTO DEMID FROM PhieuNhap WHERE MaPhieuNhap = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMPN := DEMPN + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 10 - ((LENGTH(DEMPN) + LENGTH('PN')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('PN',CHUOISOKHONG||DEMPN);
        SELECT COUNT(MaPhieuNhap) INTO DEMID FROM PhieuNhap WHERE MaPhieuNhap = ID;
    END LOOP;
    :NEW.MaPhieuNhap := ID;
END;
*/
---Tao ID KHACHHANG---
CREATE OR REPLACE TRIGGER TAO_ID_KHACH_HANG BEFORE INSERT ON KhachHang
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMKH NUMBER;
ID CHAR(10);
CHUOISOKHONG VARCHAR(8) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaKhachHang)INTO DEMKH FROM KhachHang;
    DEMKH := DEMKH +  1;
    LENGTHID := (10 - ((LENGTH(DEMKH) + LENGTH('KH'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('KH',CHUOISOKHONG||DEMKH);
    SELECT COUNT(MaKhachHang) INTO DEMID FROM KhachHang WHERE MaKhachHang = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMKH := DEMKH + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 10 - ((LENGTH(DEMKH) + LENGTH('KH')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('KH',CHUOISOKHONG||DEMKH);
        SELECT COUNT(MaKhachHang) INTO DEMID FROM KhachHang WHERE MaKhachHang = ID;
    END LOOP;
    :NEW.MaKhachHang := ID;
END;

---Tao ID DONHANG---
CREATE OR REPLACE TRIGGER TAO_ID_DON_HANG BEFORE INSERT ON DonHang
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMDH NUMBER;
ID CHAR(10);
CHUOISOKHONG VARCHAR(8) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaDonHang)INTO DEMDH FROM DonHang;
    DEMDH := DEMDH +  1;
    LENGTHID := (10 - ((LENGTH(DEMDH) + LENGTH('DH'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('DH',CHUOISOKHONG||DEMDH);
    SELECT COUNT(MaDonHang) INTO DEMID FROM DonHang WHERE MaDonHang = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMDH := DEMDH + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 10 - ((LENGTH(DEMDH) + LENGTH('DH')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('DH',CHUOISOKHONG||DEMDH);
        SELECT COUNT(MaDonHang) INTO DEMID FROM DonHang WHERE MaDonHang = ID;
    END LOOP;
    :NEW.MaDonHang := ID;
END;


---Tao ID HANGTICHDIEM---
CREATE OR REPLACE TRIGGER TAO_ID_HANG_TICH_DIEM BEFORE INSERT ON HangTichDiem
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMHANG NUMBER;
ID CHAR(5);
CHUOISOKHONG VARCHAR(4) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaHang)INTO DEMHANG FROM HangTichDiem;
    DEMHANG := DEMHANG +  1;
    LENGTHID := (5 - ((LENGTH(DEMHANG) + LENGTH('H'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('H',CHUOISOKHONG||DEMHANG);
    SELECT COUNT(MaHang) INTO DEMID FROM HangTichDiem WHERE MaHang = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMHANG := DEMHANG + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 5 - ((LENGTH(DEMHANG) + LENGTH('H')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('H',CHUOISOKHONG||DEMHANG);
        SELECT COUNT(MaHang) INTO DEMID FROM HangTichDiem WHERE MaHang = ID;
    END LOOP;
    :NEW.MaHang := ID;
END;

---Tao ID THETICHDIEM---
CREATE OR REPLACE TRIGGER TAO_ID_THE_TICH_DIEM BEFORE INSERT ON TheTichDiem
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMTHE NUMBER;
ID CHAR(10);
CHUOISOKHONG VARCHAR(9) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaThe)INTO DEMTHE FROM TheTichDiem;
    DEMTHE := DEMTHE +  1;
    LENGTHID := (10 - ((LENGTH(DEMTHE) + LENGTH('T'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('T',CHUOISOKHONG||DEMTHE);
    SELECT COUNT(MaThe) INTO DEMID FROM TheTichDiem WHERE MaThe = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMTHE := DEMTHE + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 10 - ((LENGTH(DEMTHE) + LENGTH('T')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('T',CHUOISOKHONG||DEMTHE);
        SELECT COUNT(MaThe) INTO DEMID FROM TheTichDiem WHERE MaThe = ID;
    END LOOP;
    :NEW.MaThe := ID;
END;

---Tao ID PHIEUXUAT---
CREATE OR REPLACE TRIGGER TAO_ID_PHIEU_XUAT BEFORE INSERT ON PhieuXuat
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
ID CHAR(10);
stt VARCHAR(10);
CHUOISOKHONG VARCHAR(8) := '0';
I NUMBER := 0;
LENGTHID NUMBER;
BEGIN
    stt := TRIM(:NEW.MaPhieuXuat);
    LENGTHID := (10 - ((LENGTH(stt) + LENGTH('PX'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('PX',CHUOISOKHONG|| stt);
    :NEW.MaPhieuXuat := ID;
END;
/*
---Tao ID PHIEUXUAT---
CREATE OR REPLACE TRIGGER TAO_ID_PHIEU_XUAT BEFORE INSERT ON PhieuXuat
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMPX NUMBER;
ID CHAR(10);
CHUOISOKHONG VARCHAR(8) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaPhieuXuat)INTO DEMPX FROM PhieuXuat;
    DEMPX := DEMPX +  1;
    LENGTHID := (10 - ((LENGTH(DEMPX) + LENGTH('PX'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('PX',CHUOISOKHONG||DEMPX);
    SELECT COUNT(MaPhieuXuat) INTO DEMID FROM PhieuXuat WHERE MaPhieuXuat = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMPX := DEMPX + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 10 - ((LENGTH(DEMPX) + LENGTH('PX')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('PX',CHUOISOKHONG||DEMPX);
        SELECT COUNT(MaPhieuXuat) INTO DEMID FROM PhieuXuat WHERE MaPhieuXuat = ID;
    END LOOP;
    :NEW.MaPhieuXuat := ID;
END;
*/
---Tao ID PHIEUBAOHANH---
CREATE OR REPLACE TRIGGER TAO_ID_PHIEU_BAO_HANH BEFORE INSERT ON PhieuBaoHanh
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMPBH NUMBER;
ID CHAR(10);
CHUOISOKHONG VARCHAR(8) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaPhieuBH)INTO DEMPBH FROM PhieuBaoHanh;
    DEMPBH := DEMPBH +  1;
    LENGTHID := (10 - ((LENGTH(DEMPBH) + LENGTH('BH'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('BH',CHUOISOKHONG||DEMPBH);
    SELECT COUNT(MaPhieuBH) INTO DEMID FROM PhieuBaoHanh WHERE MaPhieuBH = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMPBH := DEMPBH + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 10 - ((LENGTH(DEMPBH) + LENGTH('BH')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('BH',CHUOISOKHONG||DEMPBH);
        SELECT COUNT(MaPhieuBH) INTO DEMID FROM PhieuBaoHanh WHERE MaPhieuBH = ID;
    END LOOP;
    :NEW.MaPhieuBH := ID;
END;

---Tao ID PHANHOI---
CREATE OR REPLACE TRIGGER TAO_ID_PHAN_HOI BEFORE INSERT ON PhanHoi
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
DEMPH NUMBER;
ID CHAR(10);
CHUOISOKHONG VARCHAR(8) := '0';
I NUMBER := 0;
DEMID NUMBER;
LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MaPhanHoi)INTO DEMPH FROM PhanHoi;
    DEMPH := DEMPH +  1;
    LENGTHID := (10 - ((LENGTH(DEMPH) + LENGTH('PH'))));
    WHILE(I < LENGTHID - 1)
    LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('PH',CHUOISOKHONG||DEMPH);
    SELECT COUNT(MaPhanHoi) INTO DEMID FROM PhanHoi WHERE MaPhanHoi = ID;
    WHILE(DEMID <> 0)
    LOOP
        DEMPH := DEMPH + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 10 - ((LENGTH(DEMPH) + LENGTH('PH')));
        WHILE (I < LENGTHID - 1)
        LOOP
             CHUOISOKHONG := CONCAT(CHUOISOKHONG,'0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('PH',CHUOISOKHONG||DEMPH);
        SELECT COUNT(MaPhanHoi) INTO DEMID FROM PhanHoi WHERE MaPhanHoi = ID;
    END LOOP;
    :NEW.MaPhanHoi := ID;
END;

---Nhap kho---
CREATE OR REPLACE TRIGGER Nhap_Kho BEFORE INSERT ON ChiTietPhieuNhap
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE 
    ma_kho CHAR(5);
    CHECK_PK NUMBER(1);
BEGIN
    SELECT MaKho INTO ma_kho FROM PhieuNhap WHERE MaPhieuNhap = :NEW.MaPhieuNhap;
    SELECT COUNT(MAKHO) INTO CHECK_PK FROM CHITIETKHO WHERE MAKHO = MA_KHO AND MASANPHAM = :NEW.MASANPHAM;
    IF(CHECK_PK > 0) THEN
        UPDATE ChiTietKho SET SoLuong = SoLuong + :NEW.SoLuong WHERE MaSanPham = :NEW.MaSanPham AND MaKho = ma_kho;
    ELSE
        INSERT INTO CHITIETKHO(MAKHO, MASANPHAM, SOLUONG) VALUES(MA_KHO,:NEW.MaSanPham,:NEW.SoLuong);
    END IF;
END;

---Hoan kho---
CREATE OR REPLACE TRIGGER HOAN_KHO AFTER UPDATE ON PHIEUXUAT
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE 
---declare cursor ctpx
c_px_sp CHAR(10); 
c_px_sl NUMBER;
CURSOR c_ctpx is SELECT MaSanPham, SoLuong FROM ChiTietPhieuXuat WHERE MAPHIEUXUAT = :NEW.MAPHIEUXUAT;
BEGIN
    IF(:NEW.TRANGTHAI = 1 AND :OLD.TRANGTHAI = 0)THEN
        OPEN c_ctpx; 
        LOOP 
        FETCH c_ctpx into c_px_sp, c_px_sl; 
            EXIT WHEN c_ctpx%notfound;
            UPDATE ChiTietKho SET SoLuong = SoLuong + c_px_sl WHERE MaKho = :NEW.MAKHO AND MaSanPham = c_px_sp;
        END LOOP; 
        CLOSE c_ctpx;
    END IF;
    EXCEPTION
        WHEN OTHERS THEN
        raise_application_error(-6996,'Lỗi: Hoàn kho thất bại, kiểm tra lại mã sản phẩm trong kho!');  
END;