//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDienMay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.DONHANGs = new HashSet<DONHANG>();
            this.PHIEUBAOHANHs = new HashSet<PHIEUBAOHANH>();
            this.PHANHOIs = new HashSet<PHANHOI>();
            this.THETICHDIEMs = new HashSet<THETICHDIEM>();
        }

        public string MAKHACHHANG { get; set; }

        [Display(Name = "Họ tên")]
        [Required(ErrorMessage = "Vui lòng nhập {0}")]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Nhập {0} từ 3 - 50 ký tự")]
        [RegularExpression(@"^.{7,}$", ErrorMessage = "Nhập {0} từ 8 - 50 ký tự")]
        public string TENKHACHHANG { get; set; }

        [Display(Name = "Số điện thoại")]
        [Required(ErrorMessage = "Vui lòng nhập {0}")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "{0} gồm 10 số")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "{0} không hợp lệ")]
        public string SDT { get; set; }

        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "Vui lòng nhập {0}")]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Nhập {0} từ 8 - 50 ký tự")]
        [RegularExpression(@"^.{7,}$", ErrorMessage = "Nhập {0} từ 8 - 50 ký tự")]
        public string DIACHI { get; set; }

        public string THANHPHO { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Vui lòng nhập {0}")]
        [StringLength(50, MinimumLength = 10, ErrorMessage = "Nhập {0} từ 10 - 50 ký tự")]
        [RegularExpression(@"^.{9,}$", ErrorMessage = "Nhập {0} từ 10 - 50 ký tự")]
        [EmailAddress(ErrorMessage = "Địa chỉ {0} không hợp lệ")]
        public string EMAIL { get; set; }

        [Display(Name = "Tài khoản")]
        [Required(ErrorMessage = "Vui lòng nhập {0}")]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Nhập {0} từ 8 - 50 ký tự")]
        [RegularExpression(@"^[0-9a-zA-Z''-'\s]{1,40}$", ErrorMessage = "{0} không bao gồm ký tự đặc biệt")]
        public string TAIKHOAN { get; set; }

        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "Vui lòng nhập {0}")]
        [StringLength(32, MinimumLength = 8, ErrorMessage = "Nhập {0} từ 8 - 32 ký tự")]
        [RegularExpression(@"^.{7,}$", ErrorMessage = "Nhập {0} từ 8 - 32 ký tự")]
        public string MATKHAU { get; set; }
        public string TRANGTHAI { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUBAOHANH> PHIEUBAOHANHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANHOI> PHANHOIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THETICHDIEM> THETICHDIEMs { get; set; }
        public virtual THANHPHO THANHPHO1 { get; set; }
    }
}
