//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDienMay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.CUAHANGs = new HashSet<CUAHANG>();
            this.DONHANGs = new HashSet<DONHANG>();
            this.KHOes = new HashSet<KHO>();
            this.PHIEUNHAPs = new HashSet<PHIEUNHAP>();
            this.PHIEUXUATs = new HashSet<PHIEUXUAT>();
            this.PHIEUXUATs1 = new HashSet<PHIEUXUAT>();
        }

        public string MANHANVIEN { get; set; }

        [Display(Name = "Họ tên")]
        [Required(ErrorMessage = "Vui lòng nhập {0}")]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Nhập {0} từ 3 - 50 ký tự")]
        [RegularExpression(@"^.{7,}$", ErrorMessage = "Nhập {0} từ 8 - 50 ký tự")]
        public string TENNHANVIEN { get; set; }

        public System.DateTime NGAYSINH { get; set; }

        [Display(Name = "Số điện thoại")]
        [Required(ErrorMessage = "Vui lòng nhập {0}")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "{0} gồm 10 số")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "{0} không hợp lệ")]
        public string SDT { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Vui lòng nhập {0}")]
        [StringLength(50, MinimumLength = 10, ErrorMessage = "Nhập {0} từ 10 - 50 ký tự")]
        [RegularExpression(@"^.{9,}$", ErrorMessage = "Nhập {0} từ 10 - 50 ký tự")]
        [EmailAddress(ErrorMessage = "Địa chỉ {0} không hợp lệ")]
        public string EMAIL { get; set; }

        [Display(Name = "Địa chỉ")]
        [Required(ErrorMessage = "Vui lòng nhập {0}")]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Nhập {0} từ 8 - 50 ký tự")]
        [RegularExpression(@"^.{7,}$", ErrorMessage = "Nhập {0} từ 8 - 50 ký tự")]
        public string DIACHI { get; set; }

        [Display(Name = "Giới tính")]
        [Required(ErrorMessage = "Vui lòng chọn {0}")]
        public string GIOITINH { get; set; }

        [Display(Name = "Chức vụ")]
        [Required(ErrorMessage = "Vui lòng chọn {0}")]
        public string CHUCVU { get; set; }

        [Display(Name = "Cửa hàng")]
        [Required(ErrorMessage = "Vui lòng chọn {0}")]
        public string CUAHANG { get; set; }

        [Display(Name = "Hình thức")]
        [Required(ErrorMessage = "Vui lòng chọn {0}")]
        public string HINHTHUC { get; set; }

        [Display(Name = "Tài khoản")]
        [Required(ErrorMessage = "Vui lòng nhập {0}")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Nhập {0} từ 5 - 50 ký tự")]
        [RegularExpression(@"^[0-9a-zA-Z''-'\s]{1,40}$", ErrorMessage = "{0} không bao gồm ký tự đặc biệt")]
        public string TAIKHOAN { get; set; }
        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "Vui lòng nhập {0}")]
        [StringLength(32, MinimumLength = 8, ErrorMessage = "Nhập {0} từ 8 - 32 ký tự")]
        [RegularExpression(@"^.{7,}$", ErrorMessage = "Nhập {0} từ 8 - 32 ký tự")]
        public string MATKHAU { get; set; }

        [Display(Name = "Trạng thái")]
        [Required(ErrorMessage = "Vui lòng chọn {0}")]
        public string TRANGTHAI { get; set; }

        public virtual CHUCVU CHUCVU1 { get; set; }
        public virtual CUAHANG CUAHANG1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUAHANG> CUAHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHO> KHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUNHAP> PHIEUNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUXUAT> PHIEUXUATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUXUAT> PHIEUXUATs1 { get; set; }
    }
}
