//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDienMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUNHAP()
        {
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
        }
    
        public string MAPHIEUNHAP { get; set; }
        public string NHACUNGCAP { get; set; }
        public string NHANVIENTRUCKHO { get; set; }
        public string MAKHO { get; set; }
        public System.DateTime THOIGIANTAO { get; set; }
        public Nullable<decimal> TONGGIATRI { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        public virtual KHO KHO { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP1 { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
