//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDienMay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLDienMayEntities : DbContext
    {
        public QLDienMayEntities()
            : base("name=QLDienMayEntities")
        {
        }

        public QLDienMayEntities(string name)
            : base(name)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual DbSet<CHITIETKHO> CHITIETKHOes { get; set; }
        public virtual DbSet<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        public virtual DbSet<CHITIETPHIEUXUAT> CHITIETPHIEUXUATs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<CUAHANG> CUAHANGs { get; set; }
        public virtual DbSet<DACDIEMNOIBAT> DACDIEMNOIBATs { get; set; }
        public virtual DbSet<DANHMUC> DANHMUCs { get; set; }
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<HANGTICHDIEM> HANGTICHDIEMs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHO> KHOes { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual DbSet<LOAI> LOAIs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHANHOI> PHANHOIs { get; set; }
        public virtual DbSet<PHIEUBAOHANH> PHIEUBAOHANHs { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual DbSet<PHIEUXUAT> PHIEUXUATs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<THANHPHO> THANHPHOes { get; set; }
        public virtual DbSet<THETICHDIEM> THETICHDIEMs { get; set; }
        public virtual DbSet<THONGSOKITHUAT> THONGSOKITHUATs { get; set; }
        public virtual DbSet<TINHNANG> TINHNANGs { get; set; }
        public virtual DbSet<VOUCHER> VOUCHERs { get; set; }
    
        public virtual int PROC_DANG_KY_KHACH_HANG(string tEN_KHACH_HANG, string s_DT, string dIA_CHI, string tHANH_PHO, string e_MAIL, string tAI_KHOAN, string mAT_KHAU, ObjectParameter rETURN_VALUE)
        {
            var tEN_KHACH_HANGParameter = tEN_KHACH_HANG != null ?
                new ObjectParameter("TEN_KHACH_HANG", tEN_KHACH_HANG) :
                new ObjectParameter("TEN_KHACH_HANG", typeof(string));
    
            var s_DTParameter = s_DT != null ?
                new ObjectParameter("S_DT", s_DT) :
                new ObjectParameter("S_DT", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            var tHANH_PHOParameter = tHANH_PHO != null ?
                new ObjectParameter("THANH_PHO", tHANH_PHO) :
                new ObjectParameter("THANH_PHO", typeof(string));
    
            var e_MAILParameter = e_MAIL != null ?
                new ObjectParameter("E_MAIL", e_MAIL) :
                new ObjectParameter("E_MAIL", typeof(string));
    
            var tAI_KHOANParameter = tAI_KHOAN != null ?
                new ObjectParameter("TAI_KHOAN", tAI_KHOAN) :
                new ObjectParameter("TAI_KHOAN", typeof(string));
    
            var mAT_KHAUParameter = mAT_KHAU != null ?
                new ObjectParameter("MAT_KHAU", mAT_KHAU) :
                new ObjectParameter("MAT_KHAU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DANG_KY_KHACH_HANG", tEN_KHACH_HANGParameter, s_DTParameter, dIA_CHIParameter, tHANH_PHOParameter, e_MAILParameter, tAI_KHOANParameter, mAT_KHAUParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DANG_NHAP(string tAI_KHOAN, string mAT_KHAU, Nullable<decimal> lOAI, ObjectParameter rETURN_VALUE, ObjectParameter rETURN_ID)
        {
            var tAI_KHOANParameter = tAI_KHOAN != null ?
                new ObjectParameter("TAI_KHOAN", tAI_KHOAN) :
                new ObjectParameter("TAI_KHOAN", typeof(string));
    
            var mAT_KHAUParameter = mAT_KHAU != null ?
                new ObjectParameter("MAT_KHAU", mAT_KHAU) :
                new ObjectParameter("MAT_KHAU", typeof(string));
    
            var lOAIParameter = lOAI.HasValue ?
                new ObjectParameter("LOAI", lOAI) :
                new ObjectParameter("LOAI", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DANG_NHAP", tAI_KHOANParameter, mAT_KHAUParameter, lOAIParameter, rETURN_VALUE, rETURN_ID);
        }
    
        public virtual int PROC_DELETE_CHITIET_KHO(string mA_KHO, string mA_SAN_PHAM, ObjectParameter rETURN_VALUE)
        {
            var mA_KHOParameter = mA_KHO != null ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(string));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM != null ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_CHITIET_KHO", mA_KHOParameter, mA_SAN_PHAMParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_CHITIET_LOAI(string mA_SP, string mA_LOAI, ObjectParameter rETURN_VALUE)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var mA_LOAIParameter = mA_LOAI != null ?
                new ObjectParameter("MA_LOAI", mA_LOAI) :
                new ObjectParameter("MA_LOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_CHITIET_LOAI", mA_SPParameter, mA_LOAIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_CHUC_VU(string mA_CHUC_VU, ObjectParameter rETURN_VALUE)
        {
            var mA_CHUC_VUParameter = mA_CHUC_VU != null ?
                new ObjectParameter("MA_CHUC_VU", mA_CHUC_VU) :
                new ObjectParameter("MA_CHUC_VU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_CHUC_VU", mA_CHUC_VUParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_CUA_HANG(string mA_CUA_HANG, ObjectParameter rETURN_VALUE)
        {
            var mA_CUA_HANGParameter = mA_CUA_HANG != null ?
                new ObjectParameter("MA_CUA_HANG", mA_CUA_HANG) :
                new ObjectParameter("MA_CUA_HANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_CUA_HANG", mA_CUA_HANGParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_DAC_DIEM(string mA_SP, string tEN_DAC_DIEM, ObjectParameter rETURN_VALUE)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var tEN_DAC_DIEMParameter = tEN_DAC_DIEM != null ?
                new ObjectParameter("TEN_DAC_DIEM", tEN_DAC_DIEM) :
                new ObjectParameter("TEN_DAC_DIEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_DAC_DIEM", mA_SPParameter, tEN_DAC_DIEMParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_DANH_MUC(string mA_DANH_MUC, ObjectParameter rETURN_VALUE)
        {
            var mA_DANH_MUCParameter = mA_DANH_MUC != null ?
                new ObjectParameter("MA_DANH_MUC", mA_DANH_MUC) :
                new ObjectParameter("MA_DANH_MUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_DANH_MUC", mA_DANH_MUCParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_HANG_TICH_DIEM(string mA_HANG, ObjectParameter rETURN_VALUE)
        {
            var mA_HANGParameter = mA_HANG != null ?
                new ObjectParameter("MA_HANG", mA_HANG) :
                new ObjectParameter("MA_HANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_HANG_TICH_DIEM", mA_HANGParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_KHO(string mA_KHO, ObjectParameter rETURN_VALUE)
        {
            var mA_KHOParameter = mA_KHO != null ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_KHO", mA_KHOParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_KHUYEN_MAI(string mA_KM, ObjectParameter rETURN_VALUE)
        {
            var mA_KMParameter = mA_KM != null ?
                new ObjectParameter("MA_KM", mA_KM) :
                new ObjectParameter("MA_KM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_KHUYEN_MAI", mA_KMParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_LOAI(string mA_LOAI, ObjectParameter rETURN_VALUE)
        {
            var mA_LOAIParameter = mA_LOAI != null ?
                new ObjectParameter("MA_LOAI", mA_LOAI) :
                new ObjectParameter("MA_LOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_LOAI", mA_LOAIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_NCC(string mA_NCC, ObjectParameter rETURN_VALUE)
        {
            var mA_NCCParameter = mA_NCC != null ?
                new ObjectParameter("MA_NCC", mA_NCC) :
                new ObjectParameter("MA_NCC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_NCC", mA_NCCParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_NHAN_VIEN(string mA_NHAN_VIEN, ObjectParameter rETURN_VALUE)
        {
            var mA_NHAN_VIENParameter = mA_NHAN_VIEN != null ?
                new ObjectParameter("MA_NHAN_VIEN", mA_NHAN_VIEN) :
                new ObjectParameter("MA_NHAN_VIEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_NHAN_VIEN", mA_NHAN_VIENParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_SAN_PHAM(string mA_SAN_PHAM, ObjectParameter rETURN_VALUE)
        {
            var mA_SAN_PHAMParameter = mA_SAN_PHAM != null ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_SAN_PHAM", mA_SAN_PHAMParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_THONG_SO(string mA_SP, string tEN_THONG_SO, ObjectParameter rETURN_VALUE)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var tEN_THONG_SOParameter = tEN_THONG_SO != null ?
                new ObjectParameter("TEN_THONG_SO", tEN_THONG_SO) :
                new ObjectParameter("TEN_THONG_SO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_THONG_SO", mA_SPParameter, tEN_THONG_SOParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_TINH_NANG(string mA_SP, string tEN_TINH_NANG, ObjectParameter rETURN_VALUE)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var tEN_TINH_NANGParameter = tEN_TINH_NANG != null ?
                new ObjectParameter("TEN_TINH_NANG", tEN_TINH_NANG) :
                new ObjectParameter("TEN_TINH_NANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_TINH_NANG", mA_SPParameter, tEN_TINH_NANGParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_TP(string mA_TP, ObjectParameter rETURN_VALUE)
        {
            var mA_TPParameter = mA_TP != null ?
                new ObjectParameter("MA_TP", mA_TP) :
                new ObjectParameter("MA_TP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_TP", mA_TPParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DELETE_VOUCHER(string mA_VOUCHER, ObjectParameter rETURN_VALUE)
        {
            var mA_VOUCHERParameter = mA_VOUCHER != null ?
                new ObjectParameter("MA_VOUCHER", mA_VOUCHER) :
                new ObjectParameter("MA_VOUCHER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DELETE_VOUCHER", mA_VOUCHERParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_DOI_MAT_KHAU(string e_MAIL, Nullable<decimal> lOAI, string mAT_KHAU_MOI, ObjectParameter rETURN_VALUE)
        {
            var e_MAILParameter = e_MAIL != null ?
                new ObjectParameter("E_MAIL", e_MAIL) :
                new ObjectParameter("E_MAIL", typeof(string));
    
            var lOAIParameter = lOAI.HasValue ?
                new ObjectParameter("LOAI", lOAI) :
                new ObjectParameter("LOAI", typeof(decimal));
    
            var mAT_KHAU_MOIParameter = mAT_KHAU_MOI != null ?
                new ObjectParameter("MAT_KHAU_MOI", mAT_KHAU_MOI) :
                new ObjectParameter("MAT_KHAU_MOI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DOI_MAT_KHAU", e_MAILParameter, lOAIParameter, mAT_KHAU_MOIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_GUI_PHAN_HOI(string mA_KHACH_HANG, string nOI_DUNG, ObjectParameter rETURN_VALUE)
        {
            var mA_KHACH_HANGParameter = mA_KHACH_HANG != null ?
                new ObjectParameter("MA_KHACH_HANG", mA_KHACH_HANG) :
                new ObjectParameter("MA_KHACH_HANG", typeof(string));
    
            var nOI_DUNGParameter = nOI_DUNG != null ?
                new ObjectParameter("NOI_DUNG", nOI_DUNG) :
                new ObjectParameter("NOI_DUNG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_GUI_PHAN_HOI", mA_KHACH_HANGParameter, nOI_DUNGParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_CHITIET_KHO(string mA_KHO, string mA_SAN_PHAM, Nullable<decimal> sO_LUONG, ObjectParameter rETURN_VALUE)
        {
            var mA_KHOParameter = mA_KHO != null ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(string));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM != null ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(string));
    
            var sO_LUONGParameter = sO_LUONG.HasValue ?
                new ObjectParameter("SO_LUONG", sO_LUONG) :
                new ObjectParameter("SO_LUONG", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_CHITIET_KHO", mA_KHOParameter, mA_SAN_PHAMParameter, sO_LUONGParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_CHITIET_LOAI(string mA_SP, string mA_LOAI, ObjectParameter rETURN_VALUE)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var mA_LOAIParameter = mA_LOAI != null ?
                new ObjectParameter("MA_LOAI", mA_LOAI) :
                new ObjectParameter("MA_LOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_CHITIET_LOAI", mA_SPParameter, mA_LOAIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_CHITIET_PHIEU_NHAP(string mA_PHIEU_NHAP, string mA_SAN_PHAM, Nullable<decimal> sO_LUONG, Nullable<decimal> dON_GIA_NHAP, ObjectParameter rETURN_VALUE)
        {
            var mA_PHIEU_NHAPParameter = mA_PHIEU_NHAP != null ?
                new ObjectParameter("MA_PHIEU_NHAP", mA_PHIEU_NHAP) :
                new ObjectParameter("MA_PHIEU_NHAP", typeof(string));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM != null ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(string));
    
            var sO_LUONGParameter = sO_LUONG.HasValue ?
                new ObjectParameter("SO_LUONG", sO_LUONG) :
                new ObjectParameter("SO_LUONG", typeof(decimal));
    
            var dON_GIA_NHAPParameter = dON_GIA_NHAP.HasValue ?
                new ObjectParameter("DON_GIA_NHAP", dON_GIA_NHAP) :
                new ObjectParameter("DON_GIA_NHAP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_CHITIET_PHIEU_NHAP", mA_PHIEU_NHAPParameter, mA_SAN_PHAMParameter, sO_LUONGParameter, dON_GIA_NHAPParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_CHUC_VU(string tEN_CHUC_VU, ObjectParameter rETURN_VALUE)
        {
            var tEN_CHUC_VUParameter = tEN_CHUC_VU != null ?
                new ObjectParameter("TEN_CHUC_VU", tEN_CHUC_VU) :
                new ObjectParameter("TEN_CHUC_VU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_CHUC_VU", tEN_CHUC_VUParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_CUA_HANG(string dIA_CHI, string tHANH_PHO, string cUA_HANG_TRUONG, Nullable<System.DateTime> nGAY_THANH_LAP, ObjectParameter rETURN_VALUE)
        {
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            var tHANH_PHOParameter = tHANH_PHO != null ?
                new ObjectParameter("THANH_PHO", tHANH_PHO) :
                new ObjectParameter("THANH_PHO", typeof(string));
    
            var cUA_HANG_TRUONGParameter = cUA_HANG_TRUONG != null ?
                new ObjectParameter("CUA_HANG_TRUONG", cUA_HANG_TRUONG) :
                new ObjectParameter("CUA_HANG_TRUONG", typeof(string));
    
            var nGAY_THANH_LAPParameter = nGAY_THANH_LAP.HasValue ?
                new ObjectParameter("NGAY_THANH_LAP", nGAY_THANH_LAP) :
                new ObjectParameter("NGAY_THANH_LAP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_CUA_HANG", dIA_CHIParameter, tHANH_PHOParameter, cUA_HANG_TRUONGParameter, nGAY_THANH_LAPParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_DAC_DIEM(string mA_SP, string tEN_DAC_DIEM, ObjectParameter rETURN_VALUE)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var tEN_DAC_DIEMParameter = tEN_DAC_DIEM != null ?
                new ObjectParameter("TEN_DAC_DIEM", tEN_DAC_DIEM) :
                new ObjectParameter("TEN_DAC_DIEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_DAC_DIEM", mA_SPParameter, tEN_DAC_DIEMParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_DANH_MUC(string tEN_DANH_MUC, ObjectParameter rETURN_VALUE)
        {
            var tEN_DANH_MUCParameter = tEN_DANH_MUC != null ?
                new ObjectParameter("TEN_DANH_MUC", tEN_DANH_MUC) :
                new ObjectParameter("TEN_DANH_MUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_DANH_MUC", tEN_DANH_MUCParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_HANG_TICH_DIEM(string tEN_HANG, ObjectParameter rETURN_VALUE)
        {
            var tEN_HANGParameter = tEN_HANG != null ?
                new ObjectParameter("TEN_HANG", tEN_HANG) :
                new ObjectParameter("TEN_HANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_HANG_TICH_DIEM", tEN_HANGParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_KHO(string mA_CUA_HANG, string tRUONG_KHO, string dIA_CHI, ObjectParameter rETURN_VALUE)
        {
            var mA_CUA_HANGParameter = mA_CUA_HANG != null ?
                new ObjectParameter("MA_CUA_HANG", mA_CUA_HANG) :
                new ObjectParameter("MA_CUA_HANG", typeof(string));
    
            var tRUONG_KHOParameter = tRUONG_KHO != null ?
                new ObjectParameter("TRUONG_KHO", tRUONG_KHO) :
                new ObjectParameter("TRUONG_KHO", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_KHO", mA_CUA_HANGParameter, tRUONG_KHOParameter, dIA_CHIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_KHUYEN_MAI(string tEN_KM, Nullable<decimal> pHAN_TRAM_KHUYEN_MAI, Nullable<System.DateTime> nGAY_BAT_DAU, Nullable<System.DateTime> nGAY_KET_THUC, string mO_TA, ObjectParameter rETURN_VALUE)
        {
            var tEN_KMParameter = tEN_KM != null ?
                new ObjectParameter("TEN_KM", tEN_KM) :
                new ObjectParameter("TEN_KM", typeof(string));
    
            var pHAN_TRAM_KHUYEN_MAIParameter = pHAN_TRAM_KHUYEN_MAI.HasValue ?
                new ObjectParameter("PHAN_TRAM_KHUYEN_MAI", pHAN_TRAM_KHUYEN_MAI) :
                new ObjectParameter("PHAN_TRAM_KHUYEN_MAI", typeof(decimal));
    
            var nGAY_BAT_DAUParameter = nGAY_BAT_DAU.HasValue ?
                new ObjectParameter("NGAY_BAT_DAU", nGAY_BAT_DAU) :
                new ObjectParameter("NGAY_BAT_DAU", typeof(System.DateTime));
    
            var nGAY_KET_THUCParameter = nGAY_KET_THUC.HasValue ?
                new ObjectParameter("NGAY_KET_THUC", nGAY_KET_THUC) :
                new ObjectParameter("NGAY_KET_THUC", typeof(System.DateTime));
    
            var mO_TAParameter = mO_TA != null ?
                new ObjectParameter("MO_TA", mO_TA) :
                new ObjectParameter("MO_TA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_KHUYEN_MAI", tEN_KMParameter, pHAN_TRAM_KHUYEN_MAIParameter, nGAY_BAT_DAUParameter, nGAY_KET_THUCParameter, mO_TAParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_LOAI(string mA_DANH_MUC, string tEN_LOAI, ObjectParameter rETURN_VALUE)
        {
            var mA_DANH_MUCParameter = mA_DANH_MUC != null ?
                new ObjectParameter("MA_DANH_MUC", mA_DANH_MUC) :
                new ObjectParameter("MA_DANH_MUC", typeof(string));
    
            var tEN_LOAIParameter = tEN_LOAI != null ?
                new ObjectParameter("TEN_LOAI", tEN_LOAI) :
                new ObjectParameter("TEN_LOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_LOAI", mA_DANH_MUCParameter, tEN_LOAIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_NCC(string tEN_NCC, string mA_SO_THUE, string dIA_CHI, ObjectParameter rETURN_VALUE)
        {
            var tEN_NCCParameter = tEN_NCC != null ?
                new ObjectParameter("TEN_NCC", tEN_NCC) :
                new ObjectParameter("TEN_NCC", typeof(string));
    
            var mA_SO_THUEParameter = mA_SO_THUE != null ?
                new ObjectParameter("MA_SO_THUE", mA_SO_THUE) :
                new ObjectParameter("MA_SO_THUE", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_NCC", tEN_NCCParameter, mA_SO_THUEParameter, dIA_CHIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_NHAN_VIEN(string tEN_NV, Nullable<System.DateTime> nGAY_SINH, string s_DT, string e_MAIL, string dIA_CHI, string gIOI_TINH, string cHUC_VU, string cUA_HANG, string hINH_THUC, string tAI_KHOAN, string mAT_KHAU, string tRANG_THAI, ObjectParameter rETURN_VALUE)
        {
            var tEN_NVParameter = tEN_NV != null ?
                new ObjectParameter("TEN_NV", tEN_NV) :
                new ObjectParameter("TEN_NV", typeof(string));
    
            var nGAY_SINHParameter = nGAY_SINH.HasValue ?
                new ObjectParameter("NGAY_SINH", nGAY_SINH) :
                new ObjectParameter("NGAY_SINH", typeof(System.DateTime));
    
            var s_DTParameter = s_DT != null ?
                new ObjectParameter("S_DT", s_DT) :
                new ObjectParameter("S_DT", typeof(string));
    
            var e_MAILParameter = e_MAIL != null ?
                new ObjectParameter("E_MAIL", e_MAIL) :
                new ObjectParameter("E_MAIL", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            var gIOI_TINHParameter = gIOI_TINH != null ?
                new ObjectParameter("GIOI_TINH", gIOI_TINH) :
                new ObjectParameter("GIOI_TINH", typeof(string));
    
            var cHUC_VUParameter = cHUC_VU != null ?
                new ObjectParameter("CHUC_VU", cHUC_VU) :
                new ObjectParameter("CHUC_VU", typeof(string));
    
            var cUA_HANGParameter = cUA_HANG != null ?
                new ObjectParameter("CUA_HANG", cUA_HANG) :
                new ObjectParameter("CUA_HANG", typeof(string));
    
            var hINH_THUCParameter = hINH_THUC != null ?
                new ObjectParameter("HINH_THUC", hINH_THUC) :
                new ObjectParameter("HINH_THUC", typeof(string));
    
            var tAI_KHOANParameter = tAI_KHOAN != null ?
                new ObjectParameter("TAI_KHOAN", tAI_KHOAN) :
                new ObjectParameter("TAI_KHOAN", typeof(string));
    
            var mAT_KHAUParameter = mAT_KHAU != null ?
                new ObjectParameter("MAT_KHAU", mAT_KHAU) :
                new ObjectParameter("MAT_KHAU", typeof(string));
    
            var tRANG_THAIParameter = tRANG_THAI != null ?
                new ObjectParameter("TRANG_THAI", tRANG_THAI) :
                new ObjectParameter("TRANG_THAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_NHAN_VIEN", tEN_NVParameter, nGAY_SINHParameter, s_DTParameter, e_MAILParameter, dIA_CHIParameter, gIOI_TINHParameter, cHUC_VUParameter, cUA_HANGParameter, hINH_THUCParameter, tAI_KHOANParameter, mAT_KHAUParameter, tRANG_THAIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_PHIEU_NHAP(string nHA_CUNG_CAP, string nHAN_VIEN_TRUC_KHO, string mA_KHO, Nullable<decimal> tONG_GIA_TRI, ObjectParameter mA_PN, ObjectParameter rETURN_VALUE)
        {
            var nHA_CUNG_CAPParameter = nHA_CUNG_CAP != null ?
                new ObjectParameter("NHA_CUNG_CAP", nHA_CUNG_CAP) :
                new ObjectParameter("NHA_CUNG_CAP", typeof(string));
    
            var nHAN_VIEN_TRUC_KHOParameter = nHAN_VIEN_TRUC_KHO != null ?
                new ObjectParameter("NHAN_VIEN_TRUC_KHO", nHAN_VIEN_TRUC_KHO) :
                new ObjectParameter("NHAN_VIEN_TRUC_KHO", typeof(string));
    
            var mA_KHOParameter = mA_KHO != null ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(string));
    
            var tONG_GIA_TRIParameter = tONG_GIA_TRI.HasValue ?
                new ObjectParameter("TONG_GIA_TRI", tONG_GIA_TRI) :
                new ObjectParameter("TONG_GIA_TRI", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_PHIEU_NHAP", nHA_CUNG_CAPParameter, nHAN_VIEN_TRUC_KHOParameter, mA_KHOParameter, tONG_GIA_TRIParameter, mA_PN, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_SAN_PHAM(string tEN_SAN_PHAM, string aNH_MINH_HOA, Nullable<decimal> dON_GIA, string kHUYEN_MAI, ObjectParameter rETURN_VALUE)
        {
            var tEN_SAN_PHAMParameter = tEN_SAN_PHAM != null ?
                new ObjectParameter("TEN_SAN_PHAM", tEN_SAN_PHAM) :
                new ObjectParameter("TEN_SAN_PHAM", typeof(string));
    
            var aNH_MINH_HOAParameter = aNH_MINH_HOA != null ?
                new ObjectParameter("ANH_MINH_HOA", aNH_MINH_HOA) :
                new ObjectParameter("ANH_MINH_HOA", typeof(string));
    
            var dON_GIAParameter = dON_GIA.HasValue ?
                new ObjectParameter("DON_GIA", dON_GIA) :
                new ObjectParameter("DON_GIA", typeof(decimal));
    
            var kHUYEN_MAIParameter = kHUYEN_MAI != null ?
                new ObjectParameter("KHUYEN_MAI", kHUYEN_MAI) :
                new ObjectParameter("KHUYEN_MAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_SAN_PHAM", tEN_SAN_PHAMParameter, aNH_MINH_HOAParameter, dON_GIAParameter, kHUYEN_MAIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_THONG_SO(string mA_SP, string tEN_THONG_SO, string mO_TA, ObjectParameter rETURN_VALUE)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var tEN_THONG_SOParameter = tEN_THONG_SO != null ?
                new ObjectParameter("TEN_THONG_SO", tEN_THONG_SO) :
                new ObjectParameter("TEN_THONG_SO", typeof(string));
    
            var mO_TAParameter = mO_TA != null ?
                new ObjectParameter("MO_TA", mO_TA) :
                new ObjectParameter("MO_TA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_THONG_SO", mA_SPParameter, tEN_THONG_SOParameter, mO_TAParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_TINH_NANG(string mA_SP, string tEN_TINH_NANG, string mO_TA, string hINH_ANH, ObjectParameter rETURN_VALUE)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var tEN_TINH_NANGParameter = tEN_TINH_NANG != null ?
                new ObjectParameter("TEN_TINH_NANG", tEN_TINH_NANG) :
                new ObjectParameter("TEN_TINH_NANG", typeof(string));
    
            var mO_TAParameter = mO_TA != null ?
                new ObjectParameter("MO_TA", mO_TA) :
                new ObjectParameter("MO_TA", typeof(string));
    
            var hINH_ANHParameter = hINH_ANH != null ?
                new ObjectParameter("HINH_ANH", hINH_ANH) :
                new ObjectParameter("HINH_ANH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_TINH_NANG", mA_SPParameter, tEN_TINH_NANGParameter, mO_TAParameter, hINH_ANHParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_TP(string tEN_TP, ObjectParameter rETURN_VALUE)
        {
            var tEN_TPParameter = tEN_TP != null ?
                new ObjectParameter("TEN_TP", tEN_TP) :
                new ObjectParameter("TEN_TP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_TP", tEN_TPParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_INSERT_VOUCHER(string mA_VOUCHER, string tEN_VOUCHER, Nullable<decimal> pHAN_TRAM_KHUYEN_MAI, Nullable<System.DateTime> nGAY_BAT_DAU, Nullable<System.DateTime> nGAY_KET_THUC, string mO_TA, ObjectParameter rETURN_VALUE)
        {
            var mA_VOUCHERParameter = mA_VOUCHER != null ?
                new ObjectParameter("MA_VOUCHER", mA_VOUCHER) :
                new ObjectParameter("MA_VOUCHER", typeof(string));
    
            var tEN_VOUCHERParameter = tEN_VOUCHER != null ?
                new ObjectParameter("TEN_VOUCHER", tEN_VOUCHER) :
                new ObjectParameter("TEN_VOUCHER", typeof(string));
    
            var pHAN_TRAM_KHUYEN_MAIParameter = pHAN_TRAM_KHUYEN_MAI.HasValue ?
                new ObjectParameter("PHAN_TRAM_KHUYEN_MAI", pHAN_TRAM_KHUYEN_MAI) :
                new ObjectParameter("PHAN_TRAM_KHUYEN_MAI", typeof(decimal));
    
            var nGAY_BAT_DAUParameter = nGAY_BAT_DAU.HasValue ?
                new ObjectParameter("NGAY_BAT_DAU", nGAY_BAT_DAU) :
                new ObjectParameter("NGAY_BAT_DAU", typeof(System.DateTime));
    
            var nGAY_KET_THUCParameter = nGAY_KET_THUC.HasValue ?
                new ObjectParameter("NGAY_KET_THUC", nGAY_KET_THUC) :
                new ObjectParameter("NGAY_KET_THUC", typeof(System.DateTime));
    
            var mO_TAParameter = mO_TA != null ?
                new ObjectParameter("MO_TA", mO_TA) :
                new ObjectParameter("MO_TA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_INSERT_VOUCHER", mA_VOUCHERParameter, tEN_VOUCHERParameter, pHAN_TRAM_KHUYEN_MAIParameter, nGAY_BAT_DAUParameter, nGAY_KET_THUCParameter, mO_TAParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_KIEM_TRA_EMAIL_KHACH_HANG(string e_MAIL, ObjectParameter rETURN_VALUE)
        {
            var e_MAILParameter = e_MAIL != null ?
                new ObjectParameter("E_MAIL", e_MAIL) :
                new ObjectParameter("E_MAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_KIEM_TRA_EMAIL_KHACH_HANG", e_MAILParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_KIEM_TRA_QUYEN(string mA_NHAN_VIEN, string aCTION_NAME, string cONTROLLER_NAME, ObjectParameter rETURN_VALUE)
        {
            var mA_NHAN_VIENParameter = mA_NHAN_VIEN != null ?
                new ObjectParameter("MA_NHAN_VIEN", mA_NHAN_VIEN) :
                new ObjectParameter("MA_NHAN_VIEN", typeof(string));
    
            var aCTION_NAMEParameter = aCTION_NAME != null ?
                new ObjectParameter("ACTION_NAME", aCTION_NAME) :
                new ObjectParameter("ACTION_NAME", typeof(string));
    
            var cONTROLLER_NAMEParameter = cONTROLLER_NAME != null ?
                new ObjectParameter("CONTROLLER_NAME", cONTROLLER_NAME) :
                new ObjectParameter("CONTROLLER_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_KIEM_TRA_QUYEN", mA_NHAN_VIENParameter, aCTION_NAMEParameter, cONTROLLER_NAMEParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_TAO_DON_HANG(string mA_KHACH_HANG, string mA_CUA_HANG, string mA_VOUCHER, Nullable<decimal> tONG_GIA_TRI_DON, ObjectParameter mA_DON, ObjectParameter rETURN_VALUE)
        {
            var mA_KHACH_HANGParameter = mA_KHACH_HANG != null ?
                new ObjectParameter("MA_KHACH_HANG", mA_KHACH_HANG) :
                new ObjectParameter("MA_KHACH_HANG", typeof(string));
    
            var mA_CUA_HANGParameter = mA_CUA_HANG != null ?
                new ObjectParameter("MA_CUA_HANG", mA_CUA_HANG) :
                new ObjectParameter("MA_CUA_HANG", typeof(string));
    
            var mA_VOUCHERParameter = mA_VOUCHER != null ?
                new ObjectParameter("MA_VOUCHER", mA_VOUCHER) :
                new ObjectParameter("MA_VOUCHER", typeof(string));
    
            var tONG_GIA_TRI_DONParameter = tONG_GIA_TRI_DON.HasValue ?
                new ObjectParameter("TONG_GIA_TRI_DON", tONG_GIA_TRI_DON) :
                new ObjectParameter("TONG_GIA_TRI_DON", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_TAO_DON_HANG", mA_KHACH_HANGParameter, mA_CUA_HANGParameter, mA_VOUCHERParameter, tONG_GIA_TRI_DONParameter, mA_DON, rETURN_VALUE);
        }
    
        public virtual int PROC_TAO_THE_CHO_KHACH_HANG(string mA_KHACH_HANG, ObjectParameter rETURN_VALUE)
        {
            var mA_KHACH_HANGParameter = mA_KHACH_HANG != null ?
                new ObjectParameter("MA_KHACH_HANG", mA_KHACH_HANG) :
                new ObjectParameter("MA_KHACH_HANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_TAO_THE_CHO_KHACH_HANG", mA_KHACH_HANGParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_THANH_TOAN_DON_HANG(string mA_DON_HANG, string mA_NHAN_VIEN, string tINH_TRANG_THANH_TOAN, ObjectParameter rETURN_VALUE)
        {
            var mA_DON_HANGParameter = mA_DON_HANG != null ?
                new ObjectParameter("MA_DON_HANG", mA_DON_HANG) :
                new ObjectParameter("MA_DON_HANG", typeof(string));
    
            var mA_NHAN_VIENParameter = mA_NHAN_VIEN != null ?
                new ObjectParameter("MA_NHAN_VIEN", mA_NHAN_VIEN) :
                new ObjectParameter("MA_NHAN_VIEN", typeof(string));
    
            var tINH_TRANG_THANH_TOANParameter = tINH_TRANG_THANH_TOAN != null ?
                new ObjectParameter("TINH_TRANG_THANH_TOAN", tINH_TRANG_THANH_TOAN) :
                new ObjectParameter("TINH_TRANG_THANH_TOAN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_THANH_TOAN_DON_HANG", mA_DON_HANGParameter, mA_NHAN_VIENParameter, tINH_TRANG_THANH_TOANParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_THEM_CHI_TIET_DON_HANG(string mA_DON_HANG, string mA_SAN_PHAM, Nullable<decimal> sO_LUONG, Nullable<decimal> dON_GIA, Nullable<decimal> tHANH_TIEN, ObjectParameter rETURN_VALUE)
        {
            var mA_DON_HANGParameter = mA_DON_HANG != null ?
                new ObjectParameter("MA_DON_HANG", mA_DON_HANG) :
                new ObjectParameter("MA_DON_HANG", typeof(string));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM != null ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(string));
    
            var sO_LUONGParameter = sO_LUONG.HasValue ?
                new ObjectParameter("SO_LUONG", sO_LUONG) :
                new ObjectParameter("SO_LUONG", typeof(decimal));
    
            var dON_GIAParameter = dON_GIA.HasValue ?
                new ObjectParameter("DON_GIA", dON_GIA) :
                new ObjectParameter("DON_GIA", typeof(decimal));
    
            var tHANH_TIENParameter = tHANH_TIEN.HasValue ?
                new ObjectParameter("THANH_TIEN", tHANH_TIEN) :
                new ObjectParameter("THANH_TIEN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_THEM_CHI_TIET_DON_HANG", mA_DON_HANGParameter, mA_SAN_PHAMParameter, sO_LUONGParameter, dON_GIAParameter, tHANH_TIENParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_TINH_TRANG_GIAO_HANG(string mA_DON_HANG, string mA_NHAN_VIEN, string tINH_TRANG_GIAO_HANG, ObjectParameter rETURN_VALUE)
        {
            var mA_DON_HANGParameter = mA_DON_HANG != null ?
                new ObjectParameter("MA_DON_HANG", mA_DON_HANG) :
                new ObjectParameter("MA_DON_HANG", typeof(string));
    
            var mA_NHAN_VIENParameter = mA_NHAN_VIEN != null ?
                new ObjectParameter("MA_NHAN_VIEN", mA_NHAN_VIEN) :
                new ObjectParameter("MA_NHAN_VIEN", typeof(string));
    
            var tINH_TRANG_GIAO_HANGParameter = tINH_TRANG_GIAO_HANG != null ?
                new ObjectParameter("TINH_TRANG_GIAO_HANG", tINH_TRANG_GIAO_HANG) :
                new ObjectParameter("TINH_TRANG_GIAO_HANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_TINH_TRANG_GIAO_HANG", mA_DON_HANGParameter, mA_NHAN_VIENParameter, tINH_TRANG_GIAO_HANGParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_CHITIET_KHO(string mA_KHO, string mA_SAN_PHAM, Nullable<decimal> sO_LUONG, ObjectParameter rETURN_VALUE)
        {
            var mA_KHOParameter = mA_KHO != null ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(string));
    
            var mA_SAN_PHAMParameter = mA_SAN_PHAM != null ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(string));
    
            var sO_LUONGParameter = sO_LUONG.HasValue ?
                new ObjectParameter("SO_LUONG", sO_LUONG) :
                new ObjectParameter("SO_LUONG", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_CHITIET_KHO", mA_KHOParameter, mA_SAN_PHAMParameter, sO_LUONGParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_CHITIET_LOAI(string mA_SP, string mA_LOAI_CU, string mA_LOAI_MOI, ObjectParameter rETURN_VALUE)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var mA_LOAI_CUParameter = mA_LOAI_CU != null ?
                new ObjectParameter("MA_LOAI_CU", mA_LOAI_CU) :
                new ObjectParameter("MA_LOAI_CU", typeof(string));
    
            var mA_LOAI_MOIParameter = mA_LOAI_MOI != null ?
                new ObjectParameter("MA_LOAI_MOI", mA_LOAI_MOI) :
                new ObjectParameter("MA_LOAI_MOI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_CHITIET_LOAI", mA_SPParameter, mA_LOAI_CUParameter, mA_LOAI_MOIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_CHUC_VU(string mA_CHUC_VU, string tEN_CHUC_VU, ObjectParameter rETURN_VALUE)
        {
            var mA_CHUC_VUParameter = mA_CHUC_VU != null ?
                new ObjectParameter("MA_CHUC_VU", mA_CHUC_VU) :
                new ObjectParameter("MA_CHUC_VU", typeof(string));
    
            var tEN_CHUC_VUParameter = tEN_CHUC_VU != null ?
                new ObjectParameter("TEN_CHUC_VU", tEN_CHUC_VU) :
                new ObjectParameter("TEN_CHUC_VU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_CHUC_VU", mA_CHUC_VUParameter, tEN_CHUC_VUParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_CUA_HANG(string mA_CUA_HANG, string dIA_CHI, string tHANH_PHO, string cUA_HANG_TRUONG, Nullable<System.DateTime> nGAY_THANH_LAP, ObjectParameter rETURN_VALUE)
        {
            var mA_CUA_HANGParameter = mA_CUA_HANG != null ?
                new ObjectParameter("MA_CUA_HANG", mA_CUA_HANG) :
                new ObjectParameter("MA_CUA_HANG", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            var tHANH_PHOParameter = tHANH_PHO != null ?
                new ObjectParameter("THANH_PHO", tHANH_PHO) :
                new ObjectParameter("THANH_PHO", typeof(string));
    
            var cUA_HANG_TRUONGParameter = cUA_HANG_TRUONG != null ?
                new ObjectParameter("CUA_HANG_TRUONG", cUA_HANG_TRUONG) :
                new ObjectParameter("CUA_HANG_TRUONG", typeof(string));
    
            var nGAY_THANH_LAPParameter = nGAY_THANH_LAP.HasValue ?
                new ObjectParameter("NGAY_THANH_LAP", nGAY_THANH_LAP) :
                new ObjectParameter("NGAY_THANH_LAP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_CUA_HANG", mA_CUA_HANGParameter, dIA_CHIParameter, tHANH_PHOParameter, cUA_HANG_TRUONGParameter, nGAY_THANH_LAPParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_DAC_DIEM(string mA_SP, string tEN_DAC_DIEM_CU, string tEN_DAC_DIEM_MOI, ObjectParameter rETURN_VALUE)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var tEN_DAC_DIEM_CUParameter = tEN_DAC_DIEM_CU != null ?
                new ObjectParameter("TEN_DAC_DIEM_CU", tEN_DAC_DIEM_CU) :
                new ObjectParameter("TEN_DAC_DIEM_CU", typeof(string));
    
            var tEN_DAC_DIEM_MOIParameter = tEN_DAC_DIEM_MOI != null ?
                new ObjectParameter("TEN_DAC_DIEM_MOI", tEN_DAC_DIEM_MOI) :
                new ObjectParameter("TEN_DAC_DIEM_MOI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_DAC_DIEM", mA_SPParameter, tEN_DAC_DIEM_CUParameter, tEN_DAC_DIEM_MOIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_DANH_MUC(string mA_DANH_MUC, string tEN_DANH_MUC, ObjectParameter rETURN_VALUE)
        {
            var mA_DANH_MUCParameter = mA_DANH_MUC != null ?
                new ObjectParameter("MA_DANH_MUC", mA_DANH_MUC) :
                new ObjectParameter("MA_DANH_MUC", typeof(string));
    
            var tEN_DANH_MUCParameter = tEN_DANH_MUC != null ?
                new ObjectParameter("TEN_DANH_MUC", tEN_DANH_MUC) :
                new ObjectParameter("TEN_DANH_MUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_DANH_MUC", mA_DANH_MUCParameter, tEN_DANH_MUCParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_HANG_TICH_DIEM(string mA_HANG, string tEN_HANG, ObjectParameter rETURN_VALUE)
        {
            var mA_HANGParameter = mA_HANG != null ?
                new ObjectParameter("MA_HANG", mA_HANG) :
                new ObjectParameter("MA_HANG", typeof(string));
    
            var tEN_HANGParameter = tEN_HANG != null ?
                new ObjectParameter("TEN_HANG", tEN_HANG) :
                new ObjectParameter("TEN_HANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_HANG_TICH_DIEM", mA_HANGParameter, tEN_HANGParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_KHACH_HANG(string mA_KHACH_HANG, string tEN_KHACH_HANG, string s_DT, string dIA_CHI, string tHANH_PHO, string e_MAIL, ObjectParameter rETURN_VALUE)
        {
            var mA_KHACH_HANGParameter = mA_KHACH_HANG != null ?
                new ObjectParameter("MA_KHACH_HANG", mA_KHACH_HANG) :
                new ObjectParameter("MA_KHACH_HANG", typeof(string));
    
            var tEN_KHACH_HANGParameter = tEN_KHACH_HANG != null ?
                new ObjectParameter("TEN_KHACH_HANG", tEN_KHACH_HANG) :
                new ObjectParameter("TEN_KHACH_HANG", typeof(string));
    
            var s_DTParameter = s_DT != null ?
                new ObjectParameter("S_DT", s_DT) :
                new ObjectParameter("S_DT", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            var tHANH_PHOParameter = tHANH_PHO != null ?
                new ObjectParameter("THANH_PHO", tHANH_PHO) :
                new ObjectParameter("THANH_PHO", typeof(string));
    
            var e_MAILParameter = e_MAIL != null ?
                new ObjectParameter("E_MAIL", e_MAIL) :
                new ObjectParameter("E_MAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_KHACH_HANG", mA_KHACH_HANGParameter, tEN_KHACH_HANGParameter, s_DTParameter, dIA_CHIParameter, tHANH_PHOParameter, e_MAILParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_KHO(string mA_KHO, string mA_CUA_HANG, string tRUONG_KHO, string dIA_CHI, ObjectParameter rETURN_VALUE)
        {
            var mA_KHOParameter = mA_KHO != null ?
                new ObjectParameter("MA_KHO", mA_KHO) :
                new ObjectParameter("MA_KHO", typeof(string));
    
            var mA_CUA_HANGParameter = mA_CUA_HANG != null ?
                new ObjectParameter("MA_CUA_HANG", mA_CUA_HANG) :
                new ObjectParameter("MA_CUA_HANG", typeof(string));
    
            var tRUONG_KHOParameter = tRUONG_KHO != null ?
                new ObjectParameter("TRUONG_KHO", tRUONG_KHO) :
                new ObjectParameter("TRUONG_KHO", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_KHO", mA_KHOParameter, mA_CUA_HANGParameter, tRUONG_KHOParameter, dIA_CHIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_KHUYEN_MAI(string mA_KM, string tEN_KM, Nullable<decimal> pHAN_TRAM_KHUYEN_MAI, Nullable<System.DateTime> nGAY_BAT_DAU, Nullable<System.DateTime> nGAY_KET_THUC, string mO_TA, ObjectParameter rETURN_VALUE)
        {
            var mA_KMParameter = mA_KM != null ?
                new ObjectParameter("MA_KM", mA_KM) :
                new ObjectParameter("MA_KM", typeof(string));
    
            var tEN_KMParameter = tEN_KM != null ?
                new ObjectParameter("TEN_KM", tEN_KM) :
                new ObjectParameter("TEN_KM", typeof(string));
    
            var pHAN_TRAM_KHUYEN_MAIParameter = pHAN_TRAM_KHUYEN_MAI.HasValue ?
                new ObjectParameter("PHAN_TRAM_KHUYEN_MAI", pHAN_TRAM_KHUYEN_MAI) :
                new ObjectParameter("PHAN_TRAM_KHUYEN_MAI", typeof(decimal));
    
            var nGAY_BAT_DAUParameter = nGAY_BAT_DAU.HasValue ?
                new ObjectParameter("NGAY_BAT_DAU", nGAY_BAT_DAU) :
                new ObjectParameter("NGAY_BAT_DAU", typeof(System.DateTime));
    
            var nGAY_KET_THUCParameter = nGAY_KET_THUC.HasValue ?
                new ObjectParameter("NGAY_KET_THUC", nGAY_KET_THUC) :
                new ObjectParameter("NGAY_KET_THUC", typeof(System.DateTime));
    
            var mO_TAParameter = mO_TA != null ?
                new ObjectParameter("MO_TA", mO_TA) :
                new ObjectParameter("MO_TA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_KHUYEN_MAI", mA_KMParameter, tEN_KMParameter, pHAN_TRAM_KHUYEN_MAIParameter, nGAY_BAT_DAUParameter, nGAY_KET_THUCParameter, mO_TAParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_LOAI(string mA_LOAI, string mA_DANH_MUC, string tEN_LOAI, ObjectParameter rETURN_VALUE)
        {
            var mA_LOAIParameter = mA_LOAI != null ?
                new ObjectParameter("MA_LOAI", mA_LOAI) :
                new ObjectParameter("MA_LOAI", typeof(string));
    
            var mA_DANH_MUCParameter = mA_DANH_MUC != null ?
                new ObjectParameter("MA_DANH_MUC", mA_DANH_MUC) :
                new ObjectParameter("MA_DANH_MUC", typeof(string));
    
            var tEN_LOAIParameter = tEN_LOAI != null ?
                new ObjectParameter("TEN_LOAI", tEN_LOAI) :
                new ObjectParameter("TEN_LOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_LOAI", mA_LOAIParameter, mA_DANH_MUCParameter, tEN_LOAIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_NCC(string mA_NCC, string tEN_NCC, string mA_SO_THUE, string dIA_CHI, ObjectParameter rETURN_VALUE)
        {
            var mA_NCCParameter = mA_NCC != null ?
                new ObjectParameter("MA_NCC", mA_NCC) :
                new ObjectParameter("MA_NCC", typeof(string));
    
            var tEN_NCCParameter = tEN_NCC != null ?
                new ObjectParameter("TEN_NCC", tEN_NCC) :
                new ObjectParameter("TEN_NCC", typeof(string));
    
            var mA_SO_THUEParameter = mA_SO_THUE != null ?
                new ObjectParameter("MA_SO_THUE", mA_SO_THUE) :
                new ObjectParameter("MA_SO_THUE", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_NCC", mA_NCCParameter, tEN_NCCParameter, mA_SO_THUEParameter, dIA_CHIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_NHAN_VIEN(string mA_NHAN_VIEN, string tEN_NV, Nullable<System.DateTime> nGAY_SINH, string s_DT, string e_MAIL, string dIA_CHI, string gIOI_TINH, string cHUC_VU, string cUA_HANG, string hINH_THUC, string tAI_KHOAN, string mAT_KHAU, string tRANG_THAI, ObjectParameter rETURN_VALUE)
        {
            var mA_NHAN_VIENParameter = mA_NHAN_VIEN != null ?
                new ObjectParameter("MA_NHAN_VIEN", mA_NHAN_VIEN) :
                new ObjectParameter("MA_NHAN_VIEN", typeof(string));
    
            var tEN_NVParameter = tEN_NV != null ?
                new ObjectParameter("TEN_NV", tEN_NV) :
                new ObjectParameter("TEN_NV", typeof(string));
    
            var nGAY_SINHParameter = nGAY_SINH.HasValue ?
                new ObjectParameter("NGAY_SINH", nGAY_SINH) :
                new ObjectParameter("NGAY_SINH", typeof(System.DateTime));
    
            var s_DTParameter = s_DT != null ?
                new ObjectParameter("S_DT", s_DT) :
                new ObjectParameter("S_DT", typeof(string));
    
            var e_MAILParameter = e_MAIL != null ?
                new ObjectParameter("E_MAIL", e_MAIL) :
                new ObjectParameter("E_MAIL", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            var gIOI_TINHParameter = gIOI_TINH != null ?
                new ObjectParameter("GIOI_TINH", gIOI_TINH) :
                new ObjectParameter("GIOI_TINH", typeof(string));
    
            var cHUC_VUParameter = cHUC_VU != null ?
                new ObjectParameter("CHUC_VU", cHUC_VU) :
                new ObjectParameter("CHUC_VU", typeof(string));
    
            var cUA_HANGParameter = cUA_HANG != null ?
                new ObjectParameter("CUA_HANG", cUA_HANG) :
                new ObjectParameter("CUA_HANG", typeof(string));
    
            var hINH_THUCParameter = hINH_THUC != null ?
                new ObjectParameter("HINH_THUC", hINH_THUC) :
                new ObjectParameter("HINH_THUC", typeof(string));
    
            var tAI_KHOANParameter = tAI_KHOAN != null ?
                new ObjectParameter("TAI_KHOAN", tAI_KHOAN) :
                new ObjectParameter("TAI_KHOAN", typeof(string));
    
            var mAT_KHAUParameter = mAT_KHAU != null ?
                new ObjectParameter("MAT_KHAU", mAT_KHAU) :
                new ObjectParameter("MAT_KHAU", typeof(string));
    
            var tRANG_THAIParameter = tRANG_THAI != null ?
                new ObjectParameter("TRANG_THAI", tRANG_THAI) :
                new ObjectParameter("TRANG_THAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_NHAN_VIEN", mA_NHAN_VIENParameter, tEN_NVParameter, nGAY_SINHParameter, s_DTParameter, e_MAILParameter, dIA_CHIParameter, gIOI_TINHParameter, cHUC_VUParameter, cUA_HANGParameter, hINH_THUCParameter, tAI_KHOANParameter, mAT_KHAUParameter, tRANG_THAIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_PHIEU_BAO_HANH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_PHIEU_BAO_HANH");
        }
    
        public virtual int PROC_UPDATE_SAN_PHAM(string mA_SAN_PHAM, string tEN_SAN_PHAM, string aNH_MINH_HOA, Nullable<decimal> dON_GIA, string kHUYEN_MAI, string tRANG_THAI, ObjectParameter rETURN_VALUE)
        {
            var mA_SAN_PHAMParameter = mA_SAN_PHAM != null ?
                new ObjectParameter("MA_SAN_PHAM", mA_SAN_PHAM) :
                new ObjectParameter("MA_SAN_PHAM", typeof(string));
    
            var tEN_SAN_PHAMParameter = tEN_SAN_PHAM != null ?
                new ObjectParameter("TEN_SAN_PHAM", tEN_SAN_PHAM) :
                new ObjectParameter("TEN_SAN_PHAM", typeof(string));
    
            var aNH_MINH_HOAParameter = aNH_MINH_HOA != null ?
                new ObjectParameter("ANH_MINH_HOA", aNH_MINH_HOA) :
                new ObjectParameter("ANH_MINH_HOA", typeof(string));
    
            var dON_GIAParameter = dON_GIA.HasValue ?
                new ObjectParameter("DON_GIA", dON_GIA) :
                new ObjectParameter("DON_GIA", typeof(decimal));
    
            var kHUYEN_MAIParameter = kHUYEN_MAI != null ?
                new ObjectParameter("KHUYEN_MAI", kHUYEN_MAI) :
                new ObjectParameter("KHUYEN_MAI", typeof(string));
    
            var tRANG_THAIParameter = tRANG_THAI != null ?
                new ObjectParameter("TRANG_THAI", tRANG_THAI) :
                new ObjectParameter("TRANG_THAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_SAN_PHAM", mA_SAN_PHAMParameter, tEN_SAN_PHAMParameter, aNH_MINH_HOAParameter, dON_GIAParameter, kHUYEN_MAIParameter, tRANG_THAIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_THONG_SO(string mA_SP, string tEN_THONG_SO_CU, string tEN_THONG_SO_MOI, string mO_TA, ObjectParameter rETURN_VALUE)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var tEN_THONG_SO_CUParameter = tEN_THONG_SO_CU != null ?
                new ObjectParameter("TEN_THONG_SO_CU", tEN_THONG_SO_CU) :
                new ObjectParameter("TEN_THONG_SO_CU", typeof(string));
    
            var tEN_THONG_SO_MOIParameter = tEN_THONG_SO_MOI != null ?
                new ObjectParameter("TEN_THONG_SO_MOI", tEN_THONG_SO_MOI) :
                new ObjectParameter("TEN_THONG_SO_MOI", typeof(string));
    
            var mO_TAParameter = mO_TA != null ?
                new ObjectParameter("MO_TA", mO_TA) :
                new ObjectParameter("MO_TA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_THONG_SO", mA_SPParameter, tEN_THONG_SO_CUParameter, tEN_THONG_SO_MOIParameter, mO_TAParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_TINH_NANG(string mA_SP, string tEN_TINH_NANG_CU, string tEN_TINH_NANG_MOI, string mO_TA, string hINH_ANH, ObjectParameter rETURN_VALUE)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var tEN_TINH_NANG_CUParameter = tEN_TINH_NANG_CU != null ?
                new ObjectParameter("TEN_TINH_NANG_CU", tEN_TINH_NANG_CU) :
                new ObjectParameter("TEN_TINH_NANG_CU", typeof(string));
    
            var tEN_TINH_NANG_MOIParameter = tEN_TINH_NANG_MOI != null ?
                new ObjectParameter("TEN_TINH_NANG_MOI", tEN_TINH_NANG_MOI) :
                new ObjectParameter("TEN_TINH_NANG_MOI", typeof(string));
    
            var mO_TAParameter = mO_TA != null ?
                new ObjectParameter("MO_TA", mO_TA) :
                new ObjectParameter("MO_TA", typeof(string));
    
            var hINH_ANHParameter = hINH_ANH != null ?
                new ObjectParameter("HINH_ANH", hINH_ANH) :
                new ObjectParameter("HINH_ANH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_TINH_NANG", mA_SPParameter, tEN_TINH_NANG_CUParameter, tEN_TINH_NANG_MOIParameter, mO_TAParameter, hINH_ANHParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_TINH_TRANG_KHACH_HANG(string mA_KHACH_HANG, string tRANG_THAI, ObjectParameter rETURN_VALUE)
        {
            var mA_KHACH_HANGParameter = mA_KHACH_HANG != null ?
                new ObjectParameter("MA_KHACH_HANG", mA_KHACH_HANG) :
                new ObjectParameter("MA_KHACH_HANG", typeof(string));
    
            var tRANG_THAIParameter = tRANG_THAI != null ?
                new ObjectParameter("TRANG_THAI", tRANG_THAI) :
                new ObjectParameter("TRANG_THAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_TINH_TRANG_KHACH_HANG", mA_KHACH_HANGParameter, tRANG_THAIParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_TP(string mA_TP, string tEN_TP, ObjectParameter rETURN_VALUE)
        {
            var mA_TPParameter = mA_TP != null ?
                new ObjectParameter("MA_TP", mA_TP) :
                new ObjectParameter("MA_TP", typeof(string));
    
            var tEN_TPParameter = tEN_TP != null ?
                new ObjectParameter("TEN_TP", tEN_TP) :
                new ObjectParameter("TEN_TP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_TP", mA_TPParameter, tEN_TPParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_UPDATE_VOUCHER(string mA_VOUCHER, string tEN_VOUCHER, Nullable<decimal> pHAN_TRAM_KHUYEN_MAI, Nullable<System.DateTime> nGAY_BAT_DAU, Nullable<System.DateTime> nGAY_KET_THUC, string mO_TA, ObjectParameter rETURN_VALUE)
        {
            var mA_VOUCHERParameter = mA_VOUCHER != null ?
                new ObjectParameter("MA_VOUCHER", mA_VOUCHER) :
                new ObjectParameter("MA_VOUCHER", typeof(string));
    
            var tEN_VOUCHERParameter = tEN_VOUCHER != null ?
                new ObjectParameter("TEN_VOUCHER", tEN_VOUCHER) :
                new ObjectParameter("TEN_VOUCHER", typeof(string));
    
            var pHAN_TRAM_KHUYEN_MAIParameter = pHAN_TRAM_KHUYEN_MAI.HasValue ?
                new ObjectParameter("PHAN_TRAM_KHUYEN_MAI", pHAN_TRAM_KHUYEN_MAI) :
                new ObjectParameter("PHAN_TRAM_KHUYEN_MAI", typeof(decimal));
    
            var nGAY_BAT_DAUParameter = nGAY_BAT_DAU.HasValue ?
                new ObjectParameter("NGAY_BAT_DAU", nGAY_BAT_DAU) :
                new ObjectParameter("NGAY_BAT_DAU", typeof(System.DateTime));
    
            var nGAY_KET_THUCParameter = nGAY_KET_THUC.HasValue ?
                new ObjectParameter("NGAY_KET_THUC", nGAY_KET_THUC) :
                new ObjectParameter("NGAY_KET_THUC", typeof(System.DateTime));
    
            var mO_TAParameter = mO_TA != null ?
                new ObjectParameter("MO_TA", mO_TA) :
                new ObjectParameter("MO_TA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UPDATE_VOUCHER", mA_VOUCHERParameter, tEN_VOUCHERParameter, pHAN_TRAM_KHUYEN_MAIParameter, nGAY_BAT_DAUParameter, nGAY_KET_THUCParameter, mO_TAParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_XAC_NHAN_DON_HANG(string mA_DON_HANG, string mA_NHAN_VIEN, string tINH_TRANG_XAC_NHAN, ObjectParameter rETURN_VALUE)
        {
            var mA_DON_HANGParameter = mA_DON_HANG != null ?
                new ObjectParameter("MA_DON_HANG", mA_DON_HANG) :
                new ObjectParameter("MA_DON_HANG", typeof(string));
    
            var mA_NHAN_VIENParameter = mA_NHAN_VIEN != null ?
                new ObjectParameter("MA_NHAN_VIEN", mA_NHAN_VIEN) :
                new ObjectParameter("MA_NHAN_VIEN", typeof(string));
    
            var tINH_TRANG_XAC_NHANParameter = tINH_TRANG_XAC_NHAN != null ?
                new ObjectParameter("TINH_TRANG_XAC_NHAN", tINH_TRANG_XAC_NHAN) :
                new ObjectParameter("TINH_TRANG_XAC_NHAN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_XAC_NHAN_DON_HANG", mA_DON_HANGParameter, mA_NHAN_VIENParameter, tINH_TRANG_XAC_NHANParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_XUAT_PHIEU_XUAT_VA_BAO_HANH(string nHAN_VIEN_TAO_PHIEU, string mA_DON_HANG, ObjectParameter rETURN_VALUE)
        {
            var nHAN_VIEN_TAO_PHIEUParameter = nHAN_VIEN_TAO_PHIEU != null ?
                new ObjectParameter("NHAN_VIEN_TAO_PHIEU", nHAN_VIEN_TAO_PHIEU) :
                new ObjectParameter("NHAN_VIEN_TAO_PHIEU", typeof(string));
    
            var mA_DON_HANGParameter = mA_DON_HANG != null ?
                new ObjectParameter("MA_DON_HANG", mA_DON_HANG) :
                new ObjectParameter("MA_DON_HANG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_XUAT_PHIEU_XUAT_VA_BAO_HANH", nHAN_VIEN_TAO_PHIEUParameter, mA_DON_HANGParameter, rETURN_VALUE);
        }
    
        public virtual int PROC_XU_LY_PHAN_HOI(string mA_PHAN_HOI, ObjectParameter rETURN_VALUE)
        {
            var mA_PHAN_HOIParameter = mA_PHAN_HOI != null ?
                new ObjectParameter("MA_PHAN_HOI", mA_PHAN_HOI) :
                new ObjectParameter("MA_PHAN_HOI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_XU_LY_PHAN_HOI", mA_PHAN_HOIParameter, rETURN_VALUE);
        }
    }
}
