//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDienMay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class THETICHDIEM
    {
        [Display(Name = "Mã thẻ")]
        public string MATHE { get; set; }
        [Display(Name = "Mã khách hàng")]
        public string MAKHACHHANG { get; set; }
        [Display(Name = "Hạng")]
        public string HANG { get; set; }
        [Display(Name = "Ngày tạo")]
        public System.DateTime NGAYTAO { get; set; }
        [Display(Name = "Điểm")]
        public decimal DIEM { get; set; }
        [Display(Name = "Trạng thái")]
        public string TRANGTHAI { get; set; }

        public virtual HANGTICHDIEM HANGTICHDIEM { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
